// SPDX-License-Identifier: Apache-2.0

/**
 * Title Protocol shared type definitions (TypeScript).
 *
 * Corresponds to crates/types in the Rust workspace.
 * Spec §5
 */

// ---------------------------------------------------------------------------
// signed_json (Spec §5.1 Step 4, Step 5)
// ---------------------------------------------------------------------------

/** Signed JSON generated by the TEE. Spec §5.1 Step 4 */
export interface SignedJson {
  protocol: string;
  tee_type: string;
  /** Ed25519 public key (Base58). */
  tee_pubkey: string;
  /** Signature (Base64). */
  tee_signature: string;
  /** Attestation Document (Base64). */
  tee_attestation: string;
  payload: CorePayload | ExtensionPayload;
  attributes: Attribute[];
}

// ---------------------------------------------------------------------------
// Payload (Spec §5.1 Step 4, Step 5)
// ---------------------------------------------------------------------------

/** Core payload. Spec §5.1 Step 4 */
export interface CorePayload {
  content_hash: string;
  content_type: string;
  /** Solana wallet address (Base58). */
  creator_wallet: string;
  tsa_timestamp?: number;
  tsa_pubkey_hash?: string;
  /** RFC 3161 token (Base64). */
  tsa_token_data?: string;
  nodes: GraphNode[];
  links: GraphLink[];
}

/** Extension payload. Spec §5.1 Step 5 */
export interface ExtensionPayload {
  content_hash: string;
  content_type: string;
  creator_wallet: string;
  extension_id: string;
  wasm_source: string;
  wasm_hash: string;
  extension_input_hash?: string;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Provenance graph (Spec §2.2)
// ---------------------------------------------------------------------------

/** Provenance graph node. Spec §2.2 */
export interface GraphNode {
  id: string;
  type: "final" | "ingredient";
}

/** Provenance graph link. Spec §2.2 */
export interface GraphLink {
  source: string;
  target: string;
  role: string;
}

// ---------------------------------------------------------------------------
// Global Config (Spec §5.2 Step 1)
// ---------------------------------------------------------------------------

/** Global Config PDA. Spec §5.2 Step 1 */
export interface GlobalConfig {
  authority: string;
  core_collection_mint: string;
  ext_collection_mint: string;
  trusted_tee_nodes: TrustedTeeNode[];
  trusted_tsa_keys: string[];
  trusted_wasm_modules: TrustedWasmModule[];
}

/** Trusted TEE node. Spec §5.2 Step 1 */
export interface TrustedTeeNode {
  /** Ed25519 signing public key (Base58). */
  signing_pubkey: string;
  /** X25519 encryption public key (Base64). */
  encryption_pubkey: string;
  encryption_algorithm: string;
  /** Gateway signing public key (Base58). */
  gateway_pubkey: string;
  gateway_endpoint: string;
  status: string;
  tee_type: string;
  expected_measurements: ExpectedMeasurements;
}

/**
 * Expected TEE measurements. Key names vary by tee_type.
 * Spec §5.2 Step 1
 *
 * Conventional key names:
 * | tee_type      | Keys                           |
 * |---------------|--------------------------------|
 * | `aws_nitro`   | `PCR0`, `PCR1`, `PCR2`         |
 * | `amd_sev_snp` | `MEASUREMENT`                  |
 * | `intel_tdx`   | `MRTD`, `RTMR0` .. `RTMR3`    |
 */
export type ExpectedMeasurements = Record<string, string>;

/** Trusted WASM module. Spec §5.2 Step 1 */
export interface TrustedWasmModule {
  extension_id: string;
  wasm_source: string;
  wasm_hash: string;
}

// ---------------------------------------------------------------------------
// Encrypted payload (Spec §5.1 Step 2)
// ---------------------------------------------------------------------------

/** Encrypted payload. Spec §5.1 Step 2 */
export interface EncryptedPayload {
  /** Ephemeral X25519 public key (Base64). */
  ephemeral_pubkey: string;
  /** AES-GCM nonce (Base64). */
  nonce: string;
  /** Ciphertext (Base64). */
  ciphertext: string;
}

/** Client-constructed payload (before encryption). Spec §5.1 Step 1 */
export interface ClientPayload {
  /** Solana wallet address (Base58). */
  owner_wallet: string;
  /** Content binary (Base64). */
  content: string;
  /** C2PA sidecar manifest (Base64, optional). */
  sidecar_manifest?: string;
  extension_inputs?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// API request/response (Spec §6.2)
// ---------------------------------------------------------------------------

/** /verify request. Spec §5.1 Step 3 */
export interface VerifyRequest {
  download_url: string;
  processor_ids: string[];
}

/** /verify response. Spec §5.1 Step 6 */
export interface VerifyResponse {
  results: ProcessorResult[];
}

/** Processor result. */
export interface ProcessorResult {
  processor_id: string;
  signed_json: SignedJson;
}

/** /sign request. Spec §5.1 Step 8 */
export interface SignRequest {
  recent_blockhash: string;
  requests: SignRequestItem[];
}

/** /sign request item. */
export interface SignRequestItem {
  signed_json_uri: string;
}

/** /sign response. Spec §5.1 Step 10 */
export interface SignResponse {
  partial_txs: string[];
}

// ---------------------------------------------------------------------------
// cNFT metadata (Spec §5.1 Step 11)
// ---------------------------------------------------------------------------

/** cNFT on-chain metadata. Spec §5.1 Step 11 */
export interface CnftMetadata {
  name: string;
  symbol: string;
  uri: string;
  attributes: Attribute[];
}

/** Metaplex standard attribute. */
export interface Attribute {
  trait_type: string;
  value: string;
}

// ---------------------------------------------------------------------------
// NOTE: NodeInfo interface removed — node information is now fully on-chain
// via GlobalConfigAccount + TeeNodeAccount PDAs. Spec §6.2
