// SPDX-License-Identifier: Apache-2.0

/**
 * Title Protocol shared type definitions (TypeScript).
 *
 * Corresponds to crates/types in the Rust workspace.
 * Spec §5
 */

// ---------------------------------------------------------------------------
// signed_json (Spec §5.1 Step 4, Step 5)
// ---------------------------------------------------------------------------

/** Signed JSON generated by the TEE. Spec §5.1 Step 4 */
export interface SignedJson {
  protocol: string;
  tee_type: string;
  /** Signing algorithm used (e.g., "ed25519"). */
  tee_signature_algorithm: string;
  /** Protocol signing public key (Base64). */
  tee_pubkey: string;
  /** Signature (Base64). */
  tee_signature: string;
  /** Attestation Document (Base64). */
  tee_attestation: string;
  payload: CorePayload | ExtensionPayload;
  attributes: Attribute[];
}

// ---------------------------------------------------------------------------
// Payload (Spec §5.1 Step 4, Step 5)
// ---------------------------------------------------------------------------

/** Core payload. Spec §5.1 Step 4 */
export interface CorePayload {
  content_hash: string;
  content_type: string;
  /** Solana wallet address (Base58). */
  creator_wallet: string;
  tsa_timestamp?: number;
  tsa_pubkey_hash?: string;
  /** RFC 3161 token (Base64). */
  tsa_token_data?: string;
  nodes: GraphNode[];
  links: GraphLink[];
}

/** Extension payload. Spec §5.1 Step 5 */
export interface ExtensionPayload {
  content_hash: string;
  content_type: string;
  creator_wallet: string;
  extension_id: string;
  wasm_source: string;
  wasm_hash: string;
  extension_input_hash?: string;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Provenance graph (Spec §2.2)
// ---------------------------------------------------------------------------

/** Provenance graph node. Spec §2.2 */
export interface GraphNode {
  id: string;
  type: "final" | "ingredient";
}

/** Provenance graph link. Spec §2.2 */
export interface GraphLink {
  source: string;
  target: string;
  role: string;
}

// ---------------------------------------------------------------------------
// Global Config (Spec §5.2 Step 1)
// ---------------------------------------------------------------------------

/** Resource limits stored on-chain. Spec §6.2 */
export interface ResourceLimits {
  max_single_content_bytes?: number;
  max_concurrent_bytes?: number;
  min_upload_speed_bytes?: number;
  base_processing_time_sec?: number;
  max_global_timeout_sec?: number;
  chunk_read_timeout_sec?: number;
  c2pa_max_graph_size?: number;
}

/** WASM version entry from on-chain WasmModuleAccount. Spec §7.3 */
export interface WasmVersionInfo {
  version: number;
  /** SHA-256 hash of the WASM binary (hex-encoded). */
  wasm_hash: string;
  /** Retrievable URL for the WASM binary (e.g. ar://...). */
  wasm_source: string;
  /** 0 = active, 1 = deprecated. */
  status: number;
  registered_at: number;
}

/** WASM module with full version history from on-chain WasmModuleAccount PDA. Spec §5.2 Step 1 */
export interface WasmModuleInfo {
  extension_id: string;
  versions: WasmVersionInfo[];
}

/** Global Config PDA. Spec §5.2 Step 1 */
export interface GlobalConfig {
  authority: string;
  core_collection_mint: string;
  ext_collection_mint: string;
  trusted_tee_nodes: TrustedTeeNode[];
  trusted_tsa_keys: string[];
  trusted_wasm_modules: WasmModuleInfo[];
  resource_limits: ResourceLimits;
}

/** Trusted TEE node. Spec §5.2 Step 1 */
export interface TrustedTeeNode {
  /** Solana Ed25519 identity pubkey (Base58). PDA seed + Solana TX signing. */
  solana_pubkey: string;
  /** Protocol signing algorithm (e.g., "ed25519"). */
  signing_algorithm: string;
  /** Protocol signing public key (Base64). */
  signing_pubkey: string;
  /** Encryption algorithm (e.g., "x25519-hkdf-sha256"). */
  encryption_algorithm: string;
  /** Encryption public key (Base64). */
  encryption_pubkey: string;
  /** Gateway signing algorithm (e.g., "ed25519"). */
  gateway_signing_algorithm: string;
  /** Gateway signing public key (Base64). */
  gateway_pubkey: string;
  gateway_endpoint: string;
  status: string;
  tee_type: string;
  expected_measurements: ExpectedMeasurements;
}

/**
 * Expected TEE measurements. Key names vary by tee_type.
 * Spec §5.2 Step 1
 *
 * Conventional key names:
 * | tee_type      | Keys                           |
 * |---------------|--------------------------------|
 * | `aws_nitro`   | `PCR0`, `PCR1`, `PCR2`         |
 * | `amd_sev_snp` | `MEASUREMENT`                  |
 * | `intel_tdx`   | `MRTD`, `RTMR0` .. `RTMR3`    |
 */
export type ExpectedMeasurements = Record<string, string>;

// ---------------------------------------------------------------------------
// Encrypted payload (Spec §5.1 Step 2)
// ---------------------------------------------------------------------------
//
// Encrypted payload is a binary format stored in Temporary Storage.
// Content-Type: application/octet-stream
//
// Wire format (v1, suite_id based):
//   [1B: suite_id]
//   [2B: encap_key_len (big-endian u16)]
//   [encap_key_len bytes: encapsulated key]
//   [nonce_size bytes: nonce (suite-dependent, 12B for AES-256-GCM)]
//   [remaining: AEAD ciphertext + auth tag]
//
// Plaintext format (after decryption):
//   [4B: metadata_len (big-endian u32)]
//   [metadata_len bytes: JSON ClientMetadata]
//   [remaining: raw content bytes]
//
// See: crates/crypto/src/wire.rs

/** Client-constructed metadata (plaintext header before raw content). Spec §5.1 Step 1 */
export interface ClientMetadata {
  /** Solana wallet address (Base58). */
  owner_wallet: string;
  extension_inputs?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// API request/response (Spec §6.2)
// ---------------------------------------------------------------------------

/** /verify request. Spec §5.1 Step 3 */
export interface VerifyRequest {
  download_url: string;
  processor_ids: string[];
}

/** /verify response. Spec §5.1 Step 6 */
export interface VerifyResponse {
  results: ProcessorResult[];
}

/** Processor result. */
export interface ProcessorResult {
  processor_id: string;
  signed_json: SignedJson;
}

/** /sign request. Spec §5.1 Step 8 */
export interface SignRequest {
  recent_blockhash: string;
  requests: SignRequestItem[];
}

/** /sign request item. */
export interface SignRequestItem {
  signed_json_uri: string;
}

/** /sign response. Spec §5.1 Step 10 */
export interface SignResponse {
  partial_txs: string[];
}

// ---------------------------------------------------------------------------
// cNFT metadata (Spec §5.1 Step 11)
// ---------------------------------------------------------------------------

/** cNFT on-chain metadata. Spec §5.1 Step 11 */
export interface CnftMetadata {
  name: string;
  symbol: string;
  uri: string;
  attributes: Attribute[];
}

/** Metaplex standard attribute. */
export interface Attribute {
  trait_type: string;
  value: string;
}

