// SPDX-License-Identifier: Apache-2.0

//! Host-side helpers for the AWS Nitro attestation SP1 guest.
//!
//! Two operations are exposed:
//!
//!  * [`vkey_hash`] — return the canonical 32-byte verifying-key hash for the
//!    guest ELF. This value is what the on-chain whitelist program checks to
//!    confirm that an incoming proof was generated by *this* verifier program
//!    and not a malicious substitute. It is deterministic from the guest's
//!    source code + SP1 toolchain version; capture once and embed in the
//!    Solana program as a constant.
//!
//!  * [`generate_groth16_proof`] — given an AWS Nitro Attestation Document,
//!    run the guest under the SP1 prover and produce the Groth16 proof bytes
//!    plus public values bytes ready for the `register_key` instruction.

use sp1_sdk::{
    include_elf, CpuProver, Elf, HashableKey, ProveRequest, Prover, ProverClient, ProvingKey,
    SP1Stdin,
};

/// Guest ELF embedded at build time (compiled by `build.rs`).
pub const ATTESTATION_ELF: Elf = include_elf!("title-sp1-attestation-aws-nitro-program");

/// Build a `CpuProver` and run `setup` once. `build()` and `setup()` are
/// both async in SP1 SDK 6.2.
async fn cpu_setup() -> anyhow::Result<(CpuProver, sp1_sdk::SP1ProvingKey)> {
    let client: CpuProver = ProverClient::builder().cpu().build().await;
    let pk = client
        .setup(ATTESTATION_ELF)
        .await
        .map_err(|e| anyhow::anyhow!("SP1 setup failed: {e}"))?;
    Ok((client, pk))
}

/// Returns the 32-byte SP1 verifying-key hash for the embedded guest.
///
/// This is the value to compare against `sp1_vkey_hash` on-chain.
pub async fn vkey_hash() -> anyhow::Result<[u8; 32]> {
    let (_client, pk) = cpu_setup().await?;
    Ok(pk.verifying_key().bytes32_raw())
}

/// Output of a successful proving run.
pub struct ProofArtifacts {
    /// Groth16 proof bytes (SP1's wire format: 4-byte VK selector + Groth16 proof).
    pub proof: Vec<u8>,
    /// Public values committed by the guest. Layout documented in the guest.
    pub public_values: Vec<u8>,
    /// Verifying-key hash for the guest that produced this proof.
    pub vkey_hash: [u8; 32],
}

/// Run the prover end-to-end against the given Attestation Document.
///
/// The guest verifies the full cabundle chain — its root must match the
/// vendor root hash pinned inside `title-attestation-aws-nitro`.
pub async fn generate_groth16_proof(attestation_doc: &[u8]) -> anyhow::Result<ProofArtifacts> {
    let (client, pk) = cpu_setup().await?;

    let mut stdin = SP1Stdin::new();
    stdin.write_slice(attestation_doc);

    let proof = client
        .prove(&pk, stdin)
        .groth16()
        .await
        .map_err(|e| anyhow::anyhow!("SP1 prove failed: {e}"))?;

    Ok(ProofArtifacts {
        proof: proof.bytes(),
        public_values: proof.public_values.as_slice().to_vec(),
        vkey_hash: pk.verifying_key().bytes32_raw(),
    })
}
